name: Pipeline CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen
        run: docker build -t ildefonza/mi-primera-app:latest .

      - name: Subir imagen a Docker Hub
        run: docker push ildefonza/mi-primera-app:latest
